pipeline {
    agent any
    environment {
        imageName = 'helloworld-akasatau'
        registryCredentials = "Nexus_admin"
        registry = "172.17.0.4:8082/repository/docker/"
        dockerImage = ''
    }
    tools { 
        maven 'mvn3' 
    }
    stages {
        stage('Git')  {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Kasat1/build-t00ls.git'
            }
        }
        
        stage('Package') {
            steps {
                dir('helloworld-project/helloworld-ws/') {
                  sh 'mvn clean install'
                }
            }
        }

        stage('Building image') {
          steps{
              dir('helloworld-project/helloworld-ws/') {
                script {
                    withDockerServer([uri: 'tcp://10.0.2.15:4243']){
                  dockerImage = docker.build imageName
                    }
                }
              }
          }
        }
         stage('Uploading to Nexus') {
         steps{  
             script {
                 withDockerServer([uri: 'tcp://10.0.2.15:4243']){
                    docker.withRegistry( 'http://'+registry, registryCredentials ) {
                    dockerImage.push("rc-${env.BUILD_NUMBER}")
                    dockerImage.push("latest") }
              }
            }
          }
        }
    
        
    }
}
